### ISSUE TITLE
Can not change text font and hint font

### ISSUE THREAD

**Issue by Nastya1808** [MichaelRocks/call-me#3]
Hi Michael,
I'm trying to change a text font with a fontFamily attribute. Android Studio preview shows my text with a right font, but at runtime a default text font is shown while it is working perfectly with simple EditText fields.

**Comment by MichaelRocks** [comment]
Hi Nastya,
It seems you're trying to use a backported implementation of `fontFamily` attribute. In order to be able to use it `PhoneEditText` must be a subclass of `AppCompatEditText`, but it's a subclass of the simple `EditText`. Luckily there's a way to make it work with fonts. Two ways actually. You can use `EditText` in you XML layout file and after it's inflated call `CallMeMaybe.attachTo(editText)`. Or you can copy `PhoneEditText` class and replace `extends EditText` with `extends AppCompatEditText` and use your own version of `PhoneEditText` in XML.
